// apps/webapp/src/lib/components/Modal.svelte
<script lang="ts">
  import XMark from "$lib/components/icons/XMark.svelte";
  import PokeTime from "$lib/components/icons/PokeTime.svelte";

  export let zIndex = 5;
  export let title = "Modal";
  export let close: (() => void) | (() => never);
</script>

<div
  class="absolute-center border-2 border-black rounded-lg p-3"
  style="z-index: {zIndex}"
>
  <div class="flex justify-between items-center mb-2">
    <div class="inline-flex">
      <PokeTime class="mr-1" />
      <p>{title}</p>
    </div>

    <button on:click={close} class="cursor-pointer"><XMark /></button>
  </div>
  <div class="border border-black w-full mb-4" />

  <slot />
</div>

// apps/webapp/app/components/ui/Modal.tsx
import { XMark } from "~/components/icons/XMark";
import { PokeTime } from "~/components/icons/PokeTime";
import { useState } from "react";
import { Theme } from "~/utils/getTheme";
import { useTheme } from "~/hooks/useTheme";

interface Props {
  zIndex?: number;
  title?: string;
  onClose: (() => void) | (() => never);
  children?: React.ReactNode;
  className?: string;
}

export const Modal: React.FC<Props> = (props: Props) => {
  const [theme, setTheme] = useState<Theme>(Theme.LIGHT);
  useTheme(setTheme);

  return (
    <div
      className={`absolute-center border-2 ${theme === Theme.DARK ? "border-white" : "border-black"} rounded-lg p-3 ${props.className || ""}`}
      style={{ zIndex: props.zIndex || 5 }}
    >
      <div className="flex justify-between items-center mb-2">
        <div
          className={`inline-flex ${theme === Theme.DARK ? "text-white" : "text-black"}`}
        >
          <PokeTime className="mr-1" />
          <p>{props.title || "Modal"}</p>
        </div>

        <button onClick={props.onClose} className="cursor-pointer">
          <XMark
            className={theme === Theme.DARK ? "text-white" : "text-black"}
          />
        </button>
      </div>
      <div
        className={`border ${theme === Theme.DARK ? "border-white" : "border-black"} w-full mb-4`}
      />

      {props.children}
    </div>
  );
};

export default Modal;
